name: flutter_login
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0" # Updated to support both projects' SDK requirements

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.0
  date_picker_timeline: ^1.0.2
  flutter_date_pickers: ^0.2.0
  intl: ^0.18.0
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  shared_preferences: ^2.0.17
  swipe_cards: ^2.0.0+1
  substring_highlight: ^1.0.33
  custom_date_range_picker: ^1.0.10
  syncfusion_flutter_core: ^22.2.5
  calendar_date_picker2: ^0.5.2
  flutter_staggered_animations: ^1.1.1
  get: ^4.6.5
  swipable_stack: ^2.0.0
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  json_annotation: ^4.8.1
  font_awesome_flutter: ^10.5.0
  flutter_svg: ^2.0.7
  flutter_image_slideshow: ^0.1.6

dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1 # Use the latest version from the second project
  build_runner: ^2.4.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/
